services:
  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    command: ["server", "/data", "--console-address", ":9001"]
    restart: always
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: eHkHt1w5JgbzTfOyMSv3qhqM3NKanKGGENDiIx29

      MINIO_ACCESS_KEY: cXP6S51XS9xwDbw1insPcrdMRvjYtnn6vcDiXcPb
      MINIO_SECRET_KEY: yqpHn3lYRKWTWUeYINZecGKAUoLA3VjdWKXJq8Kn
    volumes: 
      - minio_data:/data

  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: gwYcDbNOCatziTnhyOKqVuRfOgrhZdq4GswadKJk
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      DEFAULT_ARTIFACT_ROOT: s3://mlflow-artifacts/
      AWS_ACCESS_KEY_ID: cXP6S51XS9xwDbw1insPcrdMRvjYtnn6vcDiXcPb
      AWS_SECRET_ACCESS_KEY: yqpHn3lYRKWTWUeYINZecGKAUoLA3VjdWKXJq8Kn
      BACKEND_STORE_URI: postgresql://mlflow:gwYcDbNOCatziTnhyOKqVuRfOgrhZdq4GswadKJk@postgres:5432/mlflow
    depends_on:
      - minio
      - postgres

volumes:
  minio_data:
  postgres_data:
